name: CI
on:
  push:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          yarn test
          yarn build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: page # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
